### ISSUE TITLE
 Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by arunpyasi** [jbossdemocentral/dv-odata-docker-integration-demo#3]
Hi there, 
I encountered an error Error: Invalid or corrupt jarfile /opt/jboss/jboss-dv-installer-6.0.0.GA-redhat-4.jar
INFO[0001] The command [/bin/sh -c java -jar $WORKING_DIR/$INSTALLER $WORKING_DIR/InstallationScript.xml] returned a non-zero code: 1 while running the docker build command.
FYI, I have downloaded and placed the jar file inside software directory. And while running docker build -t jbossdv600 . error occurred. Thanks :)

**Comment by kpeeples** [comment]
I pulled, copied the jar to software and ran the build which completed successfully.  Let me know what OS and docker version you are running.
